services:
  bartoc-vocabularies-webserver:
    image: lscr.io/linuxserver/nginx
    volumes:
      # nginx www data
      - $DATA/bartoc-vocabularies:/config/www
      # Required if using fancyindex module
      - $CONFIGS/nginx-fancyindex-theme.conf:/config/nginx/site-confs/default.conf
      - $DATA/nginx-fancyindex-theme/Nginx-Fancyindex-Theme-light:/config/Nginx-Fancyindex-Theme-light
    environment:
      - VIRTUAL_HOST=esx-190.gbv.de
      - VIRTUAL_PATH=/bartoc-vocabularies/
      - VIRTUAL_DEST=/
    restart: unless-stopped

networks:
  default:
    external: true
    name: nginx